# Wire up travis
language: python
sudo: false

env:
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: "latest"

services:
  - xvfb

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.6
      env: TOXENV=py3-cover,coverage
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=functional3

install:
  - travis_retry pip install tox

# For Selenium
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# http://stackoverflow.com/a/34703838/315168
# https://benlimmer.com/2019/01/14/travis-ci-xvfb/
# https://github.com/globaleaks/GlobaLeaks/commit/1788becc5dddb04a3774af63d7c03abbaf84efc9
before_script:
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-latest.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
  irc:
    channels:
      - "chat.freenode.net#pyramid"
